/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.conexionOracle;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author cuest
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    static conexionOracle co;

    public void setconexion(conexionOracle co) {
        this.co = co;
    }

    public VentanaPrincipal() {
        initComponents();
        setTitle("DDSI Proyecto Final Manuel Cuesta Rojas");
        setLocationRelativeTo(null);
        try {
            Conectar  c=new Conectar(this);
            //co = new conexionOracle();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al realizar conexión", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barramenu = new javax.swing.JMenuBar();
        Conexion = new javax.swing.JMenu();
        conectar = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        Expertos = new javax.swing.JMenu();
        gestion_expertos = new javax.swing.JMenuItem();
        colaboraciones = new javax.swing.JMenu();
        gcolaboraciones = new javax.swing.JMenuItem();
        gcolaboraciones1 = new javax.swing.JMenuItem();
        gestion = new javax.swing.JMenu();
        gestioncompleta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cuest\\OneDrive\\Documentos\\Universidad\\DDSI\\P3-DDSI\\src\\Imagenes\\imagen-fondo.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        Conexion.setText("Conexión");
        Conexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConexionActionPerformed(evt);
            }
        });

        conectar.setText("Conectar");
        conectar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        conectar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        conectar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                conectarAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarActionPerformed(evt);
            }
        });
        Conexion.add(conectar);

        salir.setText("Salir aplicación");
        salir.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        salir.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                salirAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        Conexion.add(salir);

        barramenu.add(Conexion);

        Expertos.setText("Expertos");

        gestion_expertos.setText("Gestión de expertos");
        gestion_expertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_expertosActionPerformed(evt);
            }
        });
        Expertos.add(gestion_expertos);

        barramenu.add(Expertos);

        colaboraciones.setText("Colaboraciones");

        gcolaboraciones.setText("Gestión de colaboraciones");
        gcolaboraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcolaboracionesActionPerformed(evt);
            }
        });
        colaboraciones.add(gcolaboraciones);

        gcolaboraciones1.setText("Buscar Colaboradores");
        gcolaboraciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcolaboraciones1ActionPerformed(evt);
            }
        });
        colaboraciones.add(gcolaboraciones1);

        barramenu.add(colaboraciones);

        gestion.setText("Gestion Completa");
        gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionActionPerformed(evt);
            }
        });

        gestioncompleta.setText("Gestion completa de la BD");
        gestioncompleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gestioncompleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gestioncompleta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                gestioncompletaAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        gestioncompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioncompletaActionPerformed(evt);
            }
        });
        gestion.add(gestioncompleta);

        barramenu.add(gestion);

        setJMenuBar(barramenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        try {
            if (co!=null) {
                co.DesconexionOracle();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_salirActionPerformed

    private void salirAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_salirAncestorMoved
    }//GEN-LAST:event_salirAncestorMoved

    private void gestion_expertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_expertosActionPerformed
        if (co != null) {
            VentanaExpertos ve = new VentanaExpertos(co);
            ve.setVisible(true);
        } else
            JOptionPane.showMessageDialog(null, "No estas conectado a la base de datos", "ERROR!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_gestion_expertosActionPerformed

    private void ConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConexionActionPerformed

    }//GEN-LAST:event_ConexionActionPerformed

    private void gcolaboracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcolaboracionesActionPerformed
        if (co != null) {
            VentanaColaboraciones vc = new VentanaColaboraciones(co);
            vc.setVisible(true);
        } else
            JOptionPane.showMessageDialog(null, "No estas conectado a la base de datos", "ERROR!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_gcolaboracionesActionPerformed

    private void gcolaboraciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcolaboraciones1ActionPerformed
        if (co != null) {
            BuscarColaboracion bc = new BuscarColaboracion(co);
            bc.setVisible(true);
        } else
            JOptionPane.showMessageDialog(null, "No estas conectado a la base de datos", "ERROR!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_gcolaboraciones1ActionPerformed

    private void gestioncompletaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_gestioncompletaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_gestioncompletaAncestorMoved

    private void gestioncompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioncompletaActionPerformed
        if (co != null) {

            try {
                gestioncompleta gc = new gestioncompleta(co);
                gc.setVisible(true);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "", JOptionPane.ERROR_MESSAGE);
            }
        } else
            JOptionPane.showMessageDialog(null, "No estas conectado a la base de datos", "ERROR!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_gestioncompletaActionPerformed

    private void gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionActionPerformed

    private void conectarAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_conectarAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_conectarAncestorMoved

    private void conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarActionPerformed
        Conectar c = new Conectar(this);
    }//GEN-LAST:event_conectarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Conexion;
    private javax.swing.JMenu Expertos;
    private javax.swing.JMenuBar barramenu;
    private javax.swing.JMenu colaboraciones;
    private javax.swing.JMenuItem conectar;
    private javax.swing.JMenuItem gcolaboraciones;
    private javax.swing.JMenuItem gcolaboraciones1;
    private javax.swing.JMenu gestion;
    private javax.swing.JMenuItem gestion_expertos;
    private javax.swing.JMenuItem gestioncompleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables

}
